import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/react-provider"; // Our new React Provider
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs"; // UPDATE: Clerk!

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ClarityTracking v2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* Provider Nesting:
            1. ClerkProvider (Outer): Handles "Who are you?"
            2. TRPCReactProvider (Inner): Handles "Get me data!"
          */}
          <TRPCReactProvider>
            
            {/* The Authentication Header */}
            <header className="flex justify-end items-center p-4 gap-4 h-16 border-b border-white/10 bg-white/5">
              <SignedOut>
                <SignInButton />
                <SignUpButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm px-4 py-2 hover:bg-[#5639cc] transition">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </header>

            {children}
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}